= WorkoutBook - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2113-AY1819S1-T13-5/main

By: `Team T13-5`      Since: `Sept 2018`      #Licence: `MIT`

== Introduction

WorkoutBook is for those who *prefer to use a desktop app for managing workouts*. More importantly, WorkoutBook is *optimized for those who prefer to work with a Command Line Interface* (CLI) while still having the benefits of a Graphical User Interface (GUI).

== Quick Start

.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* *`list`* : Lists all workouts in the WorkoutBook.
* **`add`**`name/commando workout type/strength duration/20m difficulty/advanced equipment/dumbbell, bench muscle/bicep, tricep calories/150 instruction/set 1: bicep curl reps: 4-6 set 2: tricep extension reps: 4-6 tag/heavy` : adds a Workout named `commando workout` to the WorkoutBook.
* **`delete`**`3` : Deletes the 3rd workout shown in the current list of workouts.
* *`exit`* : Exits the application.

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add name/NAME`, `NAME` is a parameter which can be used as `add name/commando workout`.
* Below is a list of the remaining parameters with examples of their acceptable formats:

** *_CALORIES_* are positive integers from 1 to 1000. E.g. `120`, `500`, etc.
** *_DIFFICULTY_* should only be either beginner, intermediate or advanced.
** *_DURATION_* should only be in this format: E.g. `20m`, `500m`, etc from 1m to 1000m.
** *_EQUIPMENT_* is a list of equipment separated by commas, and it should not be blank. E.g. `dumbbell,bench,mat` and `dumbbell, bench, mat` are valid.
** *_MUSCLE_* is a list of muscle groups separated by commas, and it should not be blank. E.g. `triceps,biceps,back` and `triceps, biceps, back` are valid.
** *_TYPE_* is a list of workout types separated by commas, and it should not be blank. E.g. `cardio,strength,balance` and `cardio, strength, balance` are valid.
** *_INSTRUCTION_* should only contain alphanumeric characters, punctuation, spaces, and it should not be blank. E.g. `set1: dumbbell curls reps: 4-6`.
* Items in square brackets are optional e.g `name/NAME [tag/TAG]` can be used as `name/commando workout tag/strength` or as `name/commando workout`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[tag/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `tag/strength`, `tag/strength tag/fast-paced` etc.
* Parameters can be in any order e.g. if the command specifies `name/NAME type/TYPE`, `type/TYPE name/NAME` is also acceptable.
* White spaces after a slash are automatically trimmed. For example, `add name/ commando workout` and `add name/commando workout` are the same. However, the latter is more visually pleasing.
* Duplicate parameters after one another will only take the last parameter input. For example, `add name/commando workout name/arnold workout` will only add the workout as arnold workout.
====

=== Viewing help : `help`

Format: `help`

=== Adding a workout: `add`

Adds a workout to the workout book +
Format: `add name/NAME type/TYPE duration/DURATION difficulty/DIFFICULTY equipment/EQUIPMENT muscle/MUSCLE calories/CALORIES instruction/INSTRUCTION [tag/TAG]…​`

****
* A terminal message will appear if one of the tags do not include a state tag - future, current or completed.
* The state tag is for the user to note the various things: future - untouched workouts, current - the workout that the user is currently focused on and completed - workouts that have been completed by the user.
****


[TIP]
A workout can have any number of tags (including 0)

Examples:

* `add name/commando workout type/strength, cardio duration/20m difficulty/advanced equipment/dumbbell, bench muscle/bicep, tricep calories/150 instruction/set 1: bicep curl reps: 4-6 set 2: tricep extension reps: 4-6 tag/heavy`

=== Listing all workouts : `list`

Shows a list of all workouts in the workout book. +
Format: `list`

=== Editing a workout : `edit`

Edits an existing workout in the workout book. +
Format: `edit INDEX name/NAME [type/TYPE] [duration/DURATION] [difficulty/DIFFICULTY] [equipment/EQUIPMENT] [muscle/MUSCLE] [calories/CALORIES] [instruction/INSTRUCTION] [tag/TAG]…​`

****
* Edits the workout at the specified `INDEX`. The index refers to the index number shown in the displayed workout list. The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the workout will be removed i.e adding of tags is not cumulative.
* You can remove all the workout's tags by typing `tag/` without specifying any tags after it.
****

Examples:

* `edit 1 type/strength duration/20m` +
Edits the type and duration of the 1st workout to be `strength` and `20m` respectively.
* `edit 2 name/Arnold's workout tag/` +
Edits the name of the 2nd workout to be `Arnold's workout` and clears all existing tags.

=== Changing a workout to current : `current`

Changes a workout to be a current workout in the workout book. +
Format: `current INDEX`

****
* Changes the state tag of the workout at the specified `INDEX`. The index refers to the index number shown in the displayed workout list. The index *must be a positive integer* 1, 2, 3, ...
* You can change the state tag from both `future` and `completed`.
****

Examples:

* `current 1` +
Changes the state tag of the 1st workout to be `current`.

=== Changing a workout to completed : `complete`

Changes a workout to be a completed workout in the workout book. +
Format: `complete INDEX`

****
* Changes the state tag of the workout at the specified `INDEX`. The index refers to the index number shown in the displayed workout list. The index *must be a positive integer* 1, 2, 3, ...
* You can change the state tag from both `future` and `current`.
****

Examples:

* `complete 1` +
Changes the state tag of the 1st workout to be `completed`.

=== Locating workouts by name: `filter`

Filters workouts whose types, durations, equipments contain any of the given keywords. +
Format: `filter type/TYPE duration/DURATION equipment/EQUIPMENT`

****
* The search is case insensitive. e.g `filter type/strength` will match `filter type/STRENGTH`
* The order of the keywords does not matter. e.g. `filter type/strength duration/20m` will match `filter duration/20m type/strength`
* Duration, equipment, type are searched.
****

Examples:

* `filter duration/20m equipment/dumbbell type/strength` +
Returns any workout having duration of `20m`, with equipment of `dumbbell` and of type `strength`.


=== Locating workouts by name: `find`

Finds workouts whose names contain any of the given keywords. +
Format: `find KEYWORD [MORE_KEYWORDS]`

****
* The search is case insensitive. e.g `Commando workout` will match `commando workout`
* The order of the keywords does not matter. e.g. `workout commando` will match `commando workout`
* Only the name is searched.
* Only full words will be matched e.g. `command workout` will not match `commando workout`
* workouts matching at least one keyword will be returned (i.e. `OR` search). e.g. `commando arnold's` will return `commando workout`, `Arnold's workout`
****

Examples:

* `find commando` +
Returns `command workout`.
* `find commando arnold's` +
Returns any workout having names `commando` or `arnold's`.

=== Deleting a workout : `delete`

Deletes the specified workout from the workout book. +
Format: `delete INDEX`

****
* Deletes the workout at the specified `INDEX`.
* The index refers to the index number shown in the displayed workout list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `list` +
`delete 2` +
Deletes the 2nd workout in the workout book.
* `find commando` +
`delete 1` +
Deletes the 1st workout in the results of the `find` command.

=== Selecting a workout : `select`

Selects the workout identified by the index number used in the displayed workout list. +
Format: `select INDEX`

****
* Selects the workout and loads the Google search page the workout at the specified `INDEX`.
* The index refers to the index number shown in the displayed workout list.
* The index *must be a positive integer* `1, 2, 3, ...`
****

Examples:

* `list` +
`select 2` +
Selects the 2nd workout in the workout book.
* `find commando` +
`select 1` +
Selects the 1st workout in the results of the `find` command.

=== Selecting a workout : `sort`

Sorts the workouts. +
Format: `sort`

****
* Sorts the workout.
* The index refers to the index number shown in the displayed workout list.
****

Examples:

* `add name/joe's workout type/strength duration/20m difficulty/beginner equipment/dumbbell muscle/bicep calories/200 instruction/bicep curl reps: 4-6 tag/future​` +
`sort` +
Sorts a list of all workouts in the workout book based on names after `add` a new workout.

* `delete 1` +
`sort` +
Sorts workout after `delete` a workout.

=== Listing entered commands : `history`

Lists all the commands that you have entered in reverse chronological order. +
Format: `history`

[NOTE]
====
Pressing the kbd:[&uarr;] and kbd:[&darr;] arrows will display the previous and next input respectively in the command box.
====

// tag::undoredo[]

=== Listing entered commands : `profile`

Shows the user profile. +
Format: `profile`

=== Listing entered commands : `modify`

Modify the user's profile. +
Format: `modify username/[USERNAME] gender/[GENDER] height/[HEIGHT] weight/[WEIGHT] preferred_difficulty/[DIFFICULTY]`

Examples:

* `modify username/apple` +
Change the Profile's name to apple.
* `modify username/apple height/1.82` +
Change the Profile's name to apple, height to 1.82m and update the BMI accordingly.

=== Listing entered commands : `recommend`

Recommend a workout from the existing workouts. +
Format: `recommend [calories/CALORIES] [difficulty/DIFFICULTY] [duration/DURATION]`

****
* Accepts any combinations of the three prefixes.
* At least one of the optional fields must be provided.
****

Examples:

* `recommend difficulty/beginner` +
Recommends a beginner workout.
* `recommend duration/10m calories/150` +
Recommends a 10 minute workout that burns 150 calories.
* `recommend duration/35m calories/200 difficulty/advanced` +
Recommends an advanced 35 minute workout that burns 200 calories.

=== Undoing previous command : `undo`

Restores the workout book to the state before the previous _undoable_ command was executed. +
Format: `undo`

[NOTE]
====
Undoable commands: those commands that modify the workout book's content (`add`, `delete`, `edit` and `clear`).
====

Examples:

* `delete 1` +
`list` +
`undo` (reverses the `delete 1` command) +

* `select 1` +
`list` +
`undo` +
The `undo` command fails as there are no undoable commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +

=== Redoing the previously undone command : `redo`

Reverses the most recent `undo` command. +
Format: `redo`

Examples:

* `delete 1` +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +

* `delete 1` +
`redo` +
The `redo` command fails as there are no `undo` commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +
`redo` (reapplies the `clear` command) +
// end::undoredo[]

=== Clearing all entries : `clear`

Clears all entries from the workout book. +
Format: `clear`

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Saving the data

Workout book data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

== FAQ

== Command Summary

* *Add* : `add name/NAME type/TYPE duration/DURATION difficulty/DIFFICULTY equipment/EQUIPMENT muscle/MUSCLE calories/CALORIES instruction/INSTRUCTION [tag/TAG]...` +
e.g. `add name/commando workout type/strength, cardio duration/20m difficulty/advanced equipment/dumbbell, bench muscle/bicep, tricep calories/150 instruction/set 1: bicep curl reps: 4-6 set 2: tricep extension reps: 4-6 tag/heavy`
* *Clear* : `clear`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Edit* : `edit INDEX [name/NAME] [type/TYPE] [duration/DURATION] [difficulty/DIFFICULTY] [equipment/EQUIPMENT] [muscle/MUSCLE] [calories/CALORIES] [instruction/INSTRUCTION] [tag/TAG]…​` +
e.g. `edit 1 type/light duration/25m`
* *Filter* : `filter type/TYPE duration/DURATION equipment/EQUIPMENT` +
e.g. `filter type/strength duration/20m equipment/dumbbell`
* *Find* : `find KEYWORD [MORE_KEYWORDS]` +
e.g. `find bench`
* *List* : `list`
* *Help* : `help`
* *Select* : `select INDEX` +
e.g.`select 2`
* *Sort* : `sort`
* *History* : `history`
* *Undo* : `undo`
* *Redo* : `redo`
* *Recommend* : `recommend [calories/CALORIES] [difficulty/DIFFICULTY] [duration/DURATION]` +
e.g. `recommend calories/150`
* *Modify* : `modify` +
e.g. `modify username/John Doe`
